const jocks=[ "Scientists atoms par kyun bharosa nahi karte? Kyunki woh sab kuch banate hain!",
"Maine apni patni ko kaha ki usne apne eyebrows bahut oonchi bana li hain. Uski tabiyat dekhi gayi.",
"Fake spaghetti ko kya kehte hain? An impasta!",
"Kyun nahi ladte hain skeletons ek dusre se? Unme guts nahi hote.",
"Parallel lines mein bahut kuch common hota hai. Yeh dukh ki baat hai ki kabhi nahi milenge.",
"Maine piano bajana kaano se seekha, lekin ab main apne haath aur ungliyon ka istemaal karta hoon.",
"Maine apne computer ko kaha ki mujhe ek break chahiye, aur ab woh mujhe vacation ke ads bhejna band nahi karta.",
"Mujhe sirf 25 aksharon ke alphabet pata hain. Main 'y' nahi jaanta.",
"Skeletons ek dusre se kyun nahi ladte? Unme guts nahi hote.",
"Maine apni patni ko kaha ki woh apne mistakes ko embrace kare. Usne mujhe ek hug diya.",
"Snowman aur vampire ka mix kya hota hai? Frostbite!",
"Main ek whiskey diet par hoon. Mere teen din pehle hi chale gaye hain.",
"Kyun jeet gaya scarecrow ek award? Kyunki woh apne kshetra mein outstanding tha!",
"Main ek anti-gravity par kitaab padh raha hoon. Use neeche rakhna namumkin hai!",
"Maine librarian se poocha ki kya library mein koi books paranoia par hain. Usne kaha, 'Woh tumhare peeche hain.'",
"Seagulls kyun nahi udte hain bay ke upar? Kyunki phir woh bagels ban jaayenge!",
"Math book kyun dukhi lag rahi thi? Kyunki usmein bahut saare problems the.",
"Maine apni patni ko kaha ki woh apne mistakes ko embrace kare. Usne mujhe ek hug diya.",
"Bicycle kyun gir gaya? Kyunki woh do-tired tha!",
"Maine ek can opener ko kya kehte hain jo kaam nahi karta? A can't opener!",
"Mujhe sirf 25 aksharon ke alphabet pata hain. Main 'y' nahi jaanta.",
"Scientists atoms par kyun bharosa nahi karte? Kyunki woh sab kuch banate hain!",
"Librarian se poocha ki library mein kya paranoia par books hain. Usne kaha, 'Woh tumhare peeche hain.'",
"Kyun nahi batate secrets ek farm par? Kyunki potatoes ke aankhein hain aur corn ke kaan hain!",
"Scarecrow ne award kyun jeeta? Kyunki woh apne kshetra mein outstanding tha!",
"Snowman jo six-pack wala hota hai, use kya kehte hain? An abdominal snowman!",
"Coffee ne police report kyun file ki? Usse mugged kiya gaya tha!",
"Main ek baker tha kyunki mujhe dough knead karna aata tha.",
"Fake spaghetti ko kya kehte hain? An impasta!",
"Scientists atoms par kyun bharosa nahi karte? Kyunki woh sab kuch banate hain!",
"Can opener ko kya kehte hain jo kaam nahi karta? A can't opener!",
"Mujhe sirf 25 aksharon ke alphabet pata hain. Main 'y' nahi jaanta.",
"Maine apni patni ko kaha ki woh apne mistakes ko embrace kare. Usne mujhe ek hug diya.",
"Main ek whiskey diet par hoon. Mere teen din pehle hi chale gaye hain.",
"Kyun nahi batate secrets ek farm par? Kyunki potatoes ke aankhein hain aur corn ke kaan hain!",
"Scarecrow ne award kyun jeeta? Kyunki woh apne kshetra mein outstanding tha!",
"Bicycle kyun gir gaya? Kyunki woh do-tired tha!",
"Librarian se poocha ki library mein kya paranoia par books hain. Usne kaha, 'Woh tumhare peeche hain.'",
"Snowman jo six-pack wala hota hai, use kya kehte hain? An abdominal snowman!",
"Coffee ne police report kyun file ki? Usse mugged kiya gaya tha!",
"Main ek piano bajata tha kaano se seekha, lekin ab main apne haath aur ungliyon ka istemaal karta hoon.",
"Maine apne computer ko kaha ki mujhe ek break chahiye, aur ab woh mujhe vacation ke ads bhejna band nahi karta.",
"Math book kyun dukhi lag rahi thi? Kyunki usmein bahut saare problems the.",
"Main ek anti-gravity par kitaab padh raha hoon. Use neeche rakhna namumkin hai!",
"Orange aur parrot jaisa kya hota hai? A carrot!",
"Main ek baker tha kyunki mujhe dough knead karna aata tha.",
"Scarecrow ne kyun ban gaya successful politician? Kyunki woh apne kshetra mein outstanding tha!",
"Maine apni patni ko kaha ki woh apne mistakes ko embrace kare. Usne mujhe ek hug diya.",
"Parallel lines mein bahut kuch common hota hai. Yeh dukh ki baat hai ki kabhi nahi milenge.",
"Skeletons ek dusre se kyun nahi ladte? Unme guts nahi hote.",
"Main ek whiskey diet par hoon. Mere teen din pehle hi chale gaye hain.",
"Maine apne computer ko kaha ki mujhe ek break chahiye, aur ab woh mujhe vacation ke ads bhejna band nahi karta.",
"Can opener ko kya kehte hain jo kaam nahi karta? A can't opener!",
"Mujhe sirf 25 aksharon ke alphabet pata hain. Main 'y' nahi jaanta.",
"Scientists atoms par kyun bharosa nahi karte? Kyunki woh sab kuch banate hain!",
]
let no= Math.floor(Math.random()*jocks.length);
    
document.getElementById("text").innerHTML=jocks[no]
